import { z } from "zod";
import { desc, eq } from "drizzle-orm";
import { invokeLLM } from "./_core/llm";
import { notifyOwner } from "./_core/notification";
import { storagePut } from "./storage";
import { alerts, auditEvents, evidenceAttachments, fimEvents, fleetHosts, incidentNotes, incidents, knowledgeSources, mitigationActions, notificationEvents, playbooks, ragChunks } from "../drizzle/schema";
import { getDb } from "./db";
import { COOKIE_NAME } from "@shared/const";
import { getSessionCookieOptions } from "./_core/cookies";
import { systemRouter } from "./_core/systemRouter";
import { adminProcedure, protectedProcedure, publicProcedure, router } from "./_core/trpc";

const severity = z.enum(["Critical", "High", "Medium", "Low"]);
const status = z.enum(["New", "Investigating", "Resolved"]);
const sourceMime = z.enum(["application/pdf", "text/plain"]);

async function appendAudit(actorId: number | undefined, action: string, target: string, result: string) {
  const db = await getDb(); if (!db) return;
  await db.insert(auditEvents).values({ actorId, action, target, result, chainHash: `${Date.now().toString(16)}-${Math.random().toString(16).slice(2)}` });
}
export const RAG_THRESHOLDS = { Low: 0.65, Medium: 0.75, High: 0.85, Critical: 0.95 } as const;
export function verifiedCitations(text: string, allowed: string[]) { return Array.from(text.matchAll(/\[([a-z0-9-]+)\]/gi)).map(m => m[1]).filter(id => allowed.includes(id)); }
export function hasUnsupportedCitation(text: string, allowed: string[]) { return Array.from(text.matchAll(/\[([a-z0-9-]+)\]/gi)).some(m => !allowed.includes(m[1])); }
export function evaluateRagEvidence(severityLevel: keyof typeof RAG_THRESHOLDS, topScore: number, distinctSources: number) { const minimumSources = severityLevel === "Critical" ? 4 : severityLevel === "High" ? 3 : severityLevel === "Medium" ? 2 : 1; return { accepted: topScore >= RAG_THRESHOLDS[severityLevel] && distinctSources >= minimumSources, minimumSources, threshold: RAG_THRESHOLDS[severityLevel] }; }
export function criticalNotificationRequired(level: keyof typeof RAG_THRESHOLDS) { return level === "Critical"; }
export function mitigationApprovalRequired(highImpact: boolean, role: "user" | "admin") { return highImpact && role !== "admin"; }
export function validKnowledgeUpload(mimeType: string, byteLength: number) { return ["application/pdf", "text/plain"].includes(mimeType) && byteLength > 0 && byteLength <= 50 * 1024 * 1024; }
export function validTriageTransition(nextStatus: "New" | "Investigating" | "Resolved") { return ["New", "Investigating", "Resolved"].includes(nextStatus); }

export const appRouter = router({
  system: systemRouter,
  auth: router({ me: publicProcedure.query(opts => opts.ctx.user), logout: publicProcedure.mutation(({ ctx }) => { const cookieOptions = getSessionCookieOptions(ctx.req); ctx.res.clearCookie(COOKIE_NAME, { ...cookieOptions, maxAge: -1 }); return { success: true } as const; }) }),
  soc: router({
    telemetrySnapshot: publicProcedure.query(() => ({ generatedAt: new Date(), simulated: true, alerts: [{ alertKey: "ALT-10482", title: "Ransomware encryption behavior", host: "FIN-WS-042", severity: "Critical", status: "Investigating" }, { alertKey: "ALT-10481", title: "PowerShell encoded command", host: "ENG-LT-019", severity: "High", status: "New" }, { alertKey: "ALT-10480", title: "Unsigned binary in system32", host: "DMZ-WEB-03", severity: "High", status: "Investigating" }], fim: [{ host: "FIN-WS-042", filePath: "C:\\Users\\Public\\invoice.exe", changeType: "Added", riskScore: 98, judgment: "Suspicious" }, { host: "DMZ-WEB-03", filePath: "/var/www/html/.cache.php", changeType: "Modified", riskScore: 86, judgment: "Suspicious" }], fleet: [{ hostname: "FIN-WS-042", os: "Windows 11 Enterprise", ip: "10.24.8.42", agentStatus: "Compromised" }, { hostname: "DMZ-WEB-03", os: "Ubuntu 24.04 LTS", ip: "10.24.3.19", agentStatus: "At risk" }, { hostname: "OPS-SRV-07", os: "Windows Server 2022", ip: "10.24.2.7", agentStatus: "Healthy" }], incidents: [{ incidentKey: "INC-2026-019", title: "Active encryption chain on Finance subnet", severity: "Critical", status: "Investigating" }, { incidentKey: "INC-2026-018", title: "Credential access indicators on engineering laptop", severity: "High", status: "Investigating" }], actions: [{ name: "Isolate compromised endpoint", risk: "HIGH IMPACT", status: "Approval required" }, { name: "Block malicious source IP", risk: "LOW RISK", status: "Dry-run ready" }] })),
    listAlerts: protectedProcedure.input(z.object({ severity: severity.optional(), status: status.optional() }).optional()).query(async ({ input }) => { const db = await getDb(); if (!db) return []; const rows = await db.select().from(alerts).orderBy(desc(alerts.createdAt)); return rows.filter(r => (!input?.severity || r.severity === input.severity) && (!input?.status || r.status === input.status)); }),
    updateAlert: protectedProcedure.input(z.object({ id: z.number(), status, severity: severity.optional(), assignedTo: z.number().optional() })).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) return { success: false }; await db.update(alerts).set({ status: input.status, severity: input.severity, assignedTo: input.assignedTo }).where(eq(alerts.id, input.id)); await appendAudit(ctx.user.id, "UPDATE_ALERT", String(input.id), `${input.status}${input.severity ? `/${input.severity}` : ""}`); return { success: true }; }),
    ingestAlert: protectedProcedure.input(z.object({ alertKey: z.string(), title: z.string(), host: z.string(), severity, tactic: z.string().optional(), source: z.string().optional() })).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) return { success: false }; await db.insert(alerts).values(input); if (criticalNotificationRequired(input.severity)) { const delivered = await notifyOwner({ title: `Critical SOC alert: ${input.alertKey}`, content: `${input.title} on ${input.host}. Immediate analyst review required.` }); await db.insert(notificationEvents).values({ eventType: "CriticalAlert", targetKey: input.alertKey, delivered: delivered ? 1 : 0 }); } await appendAudit(ctx.user.id, "INGEST_ALERT", input.alertKey, input.severity); return { success: true }; }),
    bulkTriage: protectedProcedure.input(z.object({ ids: z.array(z.number()).min(1), status })).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) return { success: false }; for (const id of input.ids) await db.update(alerts).set({ status: input.status }).where(eq(alerts.id, id)); await appendAudit(ctx.user.id, "BULK_TRIAGE", input.ids.join(","), input.status); return { success: true, count: input.ids.length }; }),
    assignAlert: protectedProcedure.input(z.object({ alertId: z.number(), analystId: z.number() })).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) return { success: false }; await db.update(alerts).set({ assignedTo: input.analystId }).where(eq(alerts.id, input.alertId)); await appendAudit(ctx.user.id, "ASSIGN_ALERT", String(input.alertId), String(input.analystId)); return { success: true }; }),
    askRag: protectedProcedure.input(z.object({ query: z.string().min(3), severity: severity.default("Medium") })).mutation(async ({ input, ctx }) => {
      const db = await getDb(); const candidates = db ? await db.select().from(ragChunks).orderBy(desc(ragChunks.relevance)).limit(8) : [];
      const fallback = [{ chunkKey: "fim-7a91", content: "File creation on FIN-WS-042 with SHA-256 a9f2c3…c31e." }, { chunkKey: "ids-2c04", content: "IDS ransomware signature from 10.24.8.42." }, { chunkKey: "sop-91d2", content: "Isolate endpoint and preserve volatile evidence." }];
      const evidence = candidates.length ? candidates.map(c => ({ chunkKey: c.chunkKey, content: c.content })) : fallback;
      const allowed = evidence.map(e => e.chunkKey); const topScore = candidates.length ? (candidates[0].relevance / 100) : .94; const decision = evaluateRagEvidence(input.severity, topScore, allowed.length);
      if (!decision.accepted) { await appendAudit(ctx.user.id, "RAG_QUERY_ABSTAIN", input.query.slice(0, 180), "Evidence insufficient"); return { answer: "Evidence Insufficient for Analysis.", citations: [], confidence: topScore, abstained: true }; }
      const response = await invokeLLM({ messages: [{ role: "system", content: "You are RAGSec Investigator. Answer only from supplied evidence. Every analytical claim must include an inline citation like [chunk-key]. If evidence is insufficient, say Evidence Insufficient for Analysis. Never invent IOCs." }, { role: "user", content: `Question: ${input.query}\nEvidence:\n${evidence.map(e => `[${e.chunkKey}] ${e.content}`).join("\n")}` }] });
      const answer = String(response.choices?.[0]?.message?.content || "Evidence Insufficient for Analysis."); const citations = verifiedCitations(answer, allowed); const invalid = hasUnsupportedCitation(answer, allowed); const abstained = invalid || citations.length === 0;
      await appendAudit(ctx.user.id, abstained ? "RAG_QUERY_ABSTAIN" : "RAG_QUERY", input.query.slice(0, 180), abstained ? "Citation verification failed" : "Evidence-grounded response");
      return { answer: abstained ? "Evidence Insufficient for Analysis." : answer, citations: abstained ? [] : citations, confidence: topScore, abstained };
    }),
    listIncidents: protectedProcedure.query(async () => { const db = await getDb(); return db ? db.select().from(incidents).orderBy(desc(incidents.createdAt)) : []; }),
    createIncident: protectedProcedure.input(z.object({ incidentKey: z.string(), title: z.string(), severity, alertId: z.number().optional() })).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) return { success: false }; await db.insert(incidents).values({ incidentKey: input.incidentKey, title: input.title, severity: input.severity, ownerId: ctx.user.id }); await appendAudit(ctx.user.id, "CREATE_INCIDENT", input.incidentKey, input.alertId ? `Linked alert ${input.alertId}` : "Created"); return { success: true }; }),
    addIncidentNote: protectedProcedure.input(z.object({ incidentId: z.number(), body: z.string().min(1) })).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) return { success: false }; await db.insert(incidentNotes).values({ incidentId: input.incidentId, authorId: ctx.user.id, body: input.body }); await appendAudit(ctx.user.id, "ADD_INCIDENT_NOTE", String(input.incidentId), "Committed"); return { success: true }; }),
    listEvidence: protectedProcedure.input(z.object({ incidentId: z.number() })).query(async ({ input }) => { const db = await getDb(); return db ? db.select().from(evidenceAttachments).where(eq(evidenceAttachments.incidentId, input.incidentId)).orderBy(desc(evidenceAttachments.createdAt)) : []; }),
    attachEvidenceMetadata: protectedProcedure.input(z.object({ incidentId: z.number(), name: z.string(), mimeType: z.string(), storageKey: z.string(), sha256: z.string().optional() })).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) return { success: false }; await db.insert(evidenceAttachments).values({ ...input, uploadedBy: ctx.user.id }); await appendAudit(ctx.user.id, "ATTACH_EVIDENCE", String(input.incidentId), input.name); return { success: true }; }),
    escalateIncident: protectedProcedure.input(z.object({ incidentKey: z.string(), title: z.string() })).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) return { success: false }; await db.update(incidents).set({ escalatedAt: new Date(), status: "Investigating" }).where(eq(incidents.incidentKey, input.incidentKey)); const delivered = await notifyOwner({ title: `Incident escalated: ${input.incidentKey}`, content: input.title }); await db.insert(notificationEvents).values({ eventType: "IncidentEscalated", targetKey: input.incidentKey, delivered: delivered ? 1 : 0 }); await appendAudit(ctx.user.id, "ESCALATE_INCIDENT", input.incidentKey, "Notification dispatched"); return { success: true, notified: delivered }; }),
    listFIM: protectedProcedure.query(async () => { const db = await getDb(); return db ? db.select().from(fimEvents).orderBy(desc(fimEvents.occurredAt)) : []; }),
    listFleet: protectedProcedure.query(async () => { const db = await getDb(); return db ? db.select().from(fleetHosts).orderBy(desc(fleetHosts.lastSeenAt)) : []; }),
    listSources: protectedProcedure.query(async () => { const db = await getDb(); return db ? db.select().from(knowledgeSources).orderBy(desc(knowledgeSources.createdAt)) : []; }),
    uploadKnowledgeSource: protectedProcedure.input(z.object({ name: z.string().min(1), mimeType: sourceMime, base64: z.string().min(1) })).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) return { success: false }; const raw = Buffer.from(input.base64, "base64"); if (!validKnowledgeUpload(input.mimeType, raw.byteLength)) throw new Error("Only non-empty PDF/TXT files up to 50 MB are accepted"); const stored = await storagePut(`knowledge/${ctx.user.id}/${Date.now()}-${input.name.replace(/[^a-zA-Z0-9._-]/g, "_")}`, raw, input.mimeType); await db.insert(knowledgeSources).values({ name: input.name, mimeType: input.mimeType, storageKey: stored.key, uploadedBy: ctx.user.id, ingestionStatus: "Queued" }); await appendAudit(ctx.user.id, "UPLOAD_KNOWLEDGE_SOURCE", input.name, "Queued for ingestion"); return { success: true, key: stored.key }; }),
    listPlaybooks: protectedProcedure.query(async () => { const db = await getDb(); return db ? db.select().from(playbooks).orderBy(desc(playbooks.createdAt)) : []; }),
    requestMitigation: protectedProcedure.input(z.object({ playbookId: z.number(), incidentId: z.number().optional() })).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) return { success: false }; await db.insert(mitigationActions).values({ playbookId: input.playbookId, incidentId: input.incidentId, requestedBy: ctx.user.id }); await appendAudit(ctx.user.id, "REQUEST_MITIGATION", String(input.playbookId), "Approval requested"); return { success: true, requiresApproval: true }; }),
    approveMitigation: adminProcedure.input(z.object({ actionId: z.number() })).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) return { success: false }; await db.update(mitigationActions).set({ status: "Approved" }).where(eq(mitigationActions.id, input.actionId)); await appendAudit(ctx.user.id, "APPROVE_MITIGATION", String(input.actionId), "Approved by admin"); return { success: true }; }),
    immutableAudit: protectedProcedure.query(async () => { const db = await getDb(); return db ? db.select().from(auditEvents).orderBy(desc(auditEvents.createdAt)) : []; }),
  }),
});
export type AppRouter = typeof appRouter;
