from fastapi import APIRouter, Depends, HTTPException, BackgroundTasks
from sqlalchemy.orm import Session
from datetime import datetime
from database import get_db
from auth import get_current_active_user
import models
from llm_engine import generate_mitigation
import json
import os

router = APIRouter(
    prefix="/api/actions",
    tags=["actions", "playbooks"],
    dependencies=[Depends(get_current_active_user)]
)

@router.get("/playbooks")
def get_playbooks():
    return []


# Simulated Firewall Rules File
FIREWALL_RULES_FILE = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "firewall_rules.json"))

def _write_firewall_rule(ip: str, reason: str):
    rules = []
    if os.path.exists(FIREWALL_RULES_FILE):
        try:
            with open(FIREWALL_RULES_FILE, "r") as f:
                rules = json.load(f)
        except:
            pass
    rules.append({
        "ip": ip,
        "action": "BLOCK",
        "reason": reason,
        "timestamp": datetime.utcnow().isoformat()
    })
    with open(FIREWALL_RULES_FILE, "w") as f:
        json.dump(rules, f, indent=4)

@router.post("/block-ioc")
def block_ioc(ioc: str, threat_id: str, background_tasks: BackgroundTasks, db: Session = Depends(get_db)):
    threat = db.query(models.Threat).filter(models.Threat.id == threat_id).first()
    if not threat:
        raise HTTPException(status_code=404, detail="Threat not found")
        
    # Extended Idea: Actually write the IOC to a simulated local firewall state
    background_tasks.add_task(_write_firewall_rule, ioc, f"Blocked due to Threat {threat_id}")
    
    return {
        "status": "success",
        "message": f"IOC {ioc} has been added to the enterprise blocklist.",
        "firewall_rule_generated": True
    }

@router.post("/trigger-mitigation")
def trigger_mitigation(threat_id: str, db: Session = Depends(get_db)):
    threat = db.query(models.Threat).filter(models.Threat.id == threat_id).first()
    if not threat:
        raise HTTPException(status_code=404, detail="Threat not found")
        
    # Extended Idea: Mark as mitigated in DB and generate an automated incident response summary
    threat.severity = "Resolved"
    db.commit()
    
    # Generate automated post-mortem playbook
    ai_playbook = generate_mitigation(
        threat_name=threat.name,
        threat_type=threat.type,
        severity="Resolved",
        context="Generate a post-mortem incident response summary since this threat was just mitigated.",
        cisa_solution=threat.solution or ""
    )
    
    return {
        "status": "mitigated",
        "threat_id": threat_id,
        "automated_post_mortem": ai_playbook
    }

from fastapi.responses import PlainTextResponse

@router.get("/export-report/{threat_id}", response_class=PlainTextResponse)
def export_threat_report(threat_id: str, db: Session = Depends(get_db)):
    threat = db.query(models.Threat).filter(models.Threat.id == threat_id).first()
    if not threat:
        raise HTTPException(status_code=404, detail="Threat not found")
        
    report = f"""==================================================
RAGSEC ENTERPRISE INCIDENT REPORT
==================================================
Date: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}
Threat ID: {threat.id}
Name: {threat.name}
Type: {threat.type}
Severity: {threat.severity}
Origin: {threat.origin}

[ Official Mitigation Details ]
{threat.solution or 'N/A'}

[ Exceptions / Notes ]
{threat.exceptions or 'None'}

*** GENERATED BY RAGSEC AI COMMAND CENTER ***
==================================================
"""
    # For a real PDF, we would use reportlab here, but PlainText/Markdown is easily downloadable
    return report
