/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "surface-dim": "#131313",
        "primary-fixed-dim": "#00dbe9",
        "on-secondary-container": "#5b000f",
        "on-secondary": "#680012",
        "on-surface": "#e5e2e1",
        "on-error": "#690005",
        "surface-container-low": "#1c1b1b",
        "surface-container-highest": "#353534",
        "surface": "#131313",
        "inverse-primary": "#006970",
        "tertiary-fixed-dim": "#d1bcff",
        "outline-variant": "#3b494b",
        "on-secondary-fixed": "#410008",
        "surface-variant": "#353534",
        "on-primary-fixed-variant": "#004f54",
        "primary-fixed": "#7df4ff",
        "secondary": "#ffb3b2",
        "outline": "#849495",
        "on-primary-container": "#006970",
        "on-error-container": "#ffdad6",
        "on-primary": "#00363a",
        "secondary-fixed": "#ffdad8",
        "on-primary-fixed": "#002022",
        "surface-container-lowest": "#0e0e0e",
        "primary-container": "#00f0ff",
        "error": "#ffb4ab",
        "on-tertiary": "#3c0090",
        "on-surface-variant": "#b9cacb",
        "primary": "#dbfcff",
        "surface-bright": "#3a3939",
        "on-tertiary-fixed": "#23005b",
        "on-secondary-fixed-variant": "#92001e",
        "on-tertiary-container": "#7213ff",
        "surface-tint": "#00dbe9",
        "surface-container-high": "#2a2a2a",
        "inverse-on-surface": "#313030",
        "error-container": "#93000a",
        "tertiary": "#faf3ff",
        "background": "#131313",
        "tertiary-container": "#e1d2ff",
        "secondary-fixed-dim": "#ffb3b2",
        "tertiary-fixed": "#e9ddff",
        "secondary-container": "#ff525c",
        "on-background": "#e5e2e1",
        "inverse-surface": "#e5e2e1",
        "surface-container": "#201f1f",
        "on-tertiary-fixed-variant": "#5700c9"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "md": "16px",
        "lg": "24px",
        "xs": "4px",
        "sm": "8px",
        "gutter": "16px",
        "xl": "40px",
        "margin": "24px",
        "unit": "4px"
      },
      "fontFamily": {
        "headline-md": ["Inter"],
        "display-lg": ["Inter"],
        "body-md": ["Inter"],
        "label-caps": ["JetBrains Mono"],
        "headline-lg": ["Inter"],
        "body-lg": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "code-md": ["JetBrains Mono"]
      },
      "fontSize": {
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "36px", "fontWeight": "600" }],
        "code-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
